name: Push to RubyGems

on:
  push:
    branches: [ main ]

jobs:
  push:
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest
    env:
      BUNDLE_LOCKFILE: Gemfile.lock

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: rubygems/release-gem@v1
